#!/bin/sh

set -e

#DEBHELPER#

for cert in /usr/share/dnie-support/certs/*; do
	certname=$(basename ${cert})
	certutil -D -n "${certname}" -d /etc/firefox/profile 2>> /var/log/syslog || true
	[ $? = 0 ] && echo "Certificate \"${certname}\" deleted to database."
done

modutil -force -delete "OpenSC PKCS#11 Module" -libfile /usr/lib/opensc-pkcs11.so -dbdir /etc/firefox/profile 2>> /var/log/syslog || true
